# SPDX-FileCopyrightText: 2020 Léo Masson <lmasson@edhebi.info>
#
# SPDX-License-Identifier: Zlib

unstable_features = true
emit_mode = "Files"

error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_strings = true
merge_imports = true
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
